# determine OS
if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    set(GLUCENT_OS_WINDOWS 1)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    if(ANDROID)
        message(FATAL_ERROR "Unfortunately glucent doesn't support Android")
    else()
        set(GLUCENT_OS_LINUX 1)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    if(IOS)
        message(FATAL_ERROR "Unfortunately glucent doesn't support iOS")
    else()
        set(GLUCENT_OS_MACOSX 1)
    endif()
else()
    message(FATAL_ERROR "Unsupported OS or environment")
    return()
endif()

set(GLUCENT_INSTALL_DIR "/${CMAKE_INSTALL_LIBDIR}/pkgconfig")

if(MSVC)
    set(GLUCENT_COMPILER_MSVC 1)

    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(GLUCENT_COMPILER_CLANG_CL 1)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(GLUCENT_COMPILER_CLANG 1)
elseif(CMAKE_COMPILER_IS_GNUCXX)
    set(GLUCENT_COMPILER_GCC 1)
else()
    message(FATAL_ERROR "Unsupported compiler")
    return()
endif()
